### ISSUE TITLE
How to run the demo?

### ISSUE THREAD

**Issue by opentld** [athn-nik/teach#6] opened 2022-10-07 14:49 UTC
Did someone successfully run the demo? What's wrong with my commands?
![image](https://user-images.githubusercontent.com/21096515/194582067-0b932a4b-a7b5-48b1-b455-715c68334516.png)
Who can give an example of a correct run of demo?

**Comment by opentld** [comment] 2022-10-07 14:54
by the way, the address of website that the "Running the Demo" provided :  https://github.com/athn-nik/teach/blob/main/teach.is.tue.mpg.de is 404 :(
![image](https://user-images.githubusercontent.com/21096515/194582828-9ebb22b8-99c2-4abb-a198-f418a9dfbc55.png)

**Comment by opentld** [comment] 2022-10-07 15:05
(teach-env) D:\SourceCodes\Pose\3D\teach>python interact_teach.py folder=./ output=./ texts=run durs=3
Global seed set to 1234
[07/10/22 23:05:26][__main__][INFO] - Loading model
['D:\\SourceCodes\\Pose\\3D\\teach\\deps', 'distilbert-base-uncased']
Error executing job with overrides: ['folder=./', 'output=./', 'texts=run', 'durs=3']
Traceback (most recent call last):
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\text_hist.py", line 39, in __init__
    super().__init__(modelpath=modelpath, finetune=finetune)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\distilbert.py", line 41, in __init__
    rel_p = rel_p[rel_p.index('deps'):]
ValueError: 'deps' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\teach.py", line 51, in __init__
    self.textencoder = instantiate(textencoder, nfeats=nfeats)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\text_hist.py", line 39, in __init__
    super().__init__(modelpath=modelpath, finetune=finetune)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\distilbert.py", line 41, in __init__
    rel_p = rel_p[rel_p.index('deps'):]
ValueError: Error instantiating 'teach.model.textencoder.text_hist.TextHist' : 'deps' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SourceCodes\Pose\3D\teach\interact_teach.py", line 35, in _interact
    return interact(cfg)
  File "D:\SourceCodes\Pose\3D\teach\interact_teach.py", line 57, in interact
    model = instantiate(cfg.model,
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\teach.py", line 51, in __init__
    self.textencoder = instantiate(textencoder, nfeats=nfeats)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\text_hist.py", line 39, in __init__
    super().__init__(modelpath=modelpath, finetune=finetune)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\distilbert.py", line 41, in __init__
    rel_p = rel_p[rel_p.index('deps'):]
ValueError: Error instantiating 'teach.model.teach.TEACH' : Error instantiating 'teach.model.textencoder.text_hist.TextHist' : 'deps' is not in list

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by opentld** [comment] 2022-10-07 15:06
(teach-env) D:\SourceCodes\Pose\3D\teach>python interact_teach.py folder=./ output=./ texts=run durs=3
Global seed set to 1234
[07/10/22 23:05:26][__main__][INFO] - Loading model
Error executing job with overrides: ['folder=./', 'output=./', 'texts=run', 'durs=3']
Traceback (most recent call last):
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\text_hist.py", line 39, in __init__
    super().__init__(modelpath=modelpath, finetune=finetune)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\distilbert.py", line 41, in __init__
    rel_p = rel_p[rel_p.index('deps'):]
ValueError: 'deps' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\teach.py", line 51, in __init__
    self.textencoder = instantiate(textencoder, nfeats=nfeats)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\text_hist.py", line 39, in __init__
    super().__init__(modelpath=modelpath, finetune=finetune)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\distilbert.py", line 41, in __init__
    rel_p = rel_p[rel_p.index('deps'):]
ValueError: Error instantiating 'teach.model.textencoder.text_hist.TextHist' : 'deps' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SourceCodes\Pose\3D\teach\interact_teach.py", line 35, in _interact
    return interact(cfg)
  File "D:\SourceCodes\Pose\3D\teach\interact_teach.py", line 57, in interact
    model = instantiate(cfg.model,
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\teach.py", line 51, in __init__
    self.textencoder = instantiate(textencoder, nfeats=nfeats)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\text_hist.py", line 39, in __init__
    super().__init__(modelpath=modelpath, finetune=finetune)
  File "D:\SourceCodes\Pose\3D\teach\teach\model\textencoder\distilbert.py", line 41, in __init__
    rel_p = rel_p[rel_p.index('deps'):]
ValueError: Error instantiating 'teach.model.teach.TEACH' : Error instantiating 'teach.model.textencoder.text_hist.TextHist' : 'deps' is not in list

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by atnikos** [comment] 2022-10-07 15:09
Hello @opentld ,
I fixed the link you can now access it, or click in the top of the readme where is a button for the website.
Sign up to access the download section. Download the required files by clicking on the corresponding link (eg. TEACH) then unzip it and put its contents in a folder. This folder is supposed to be given in the `folder` argument for the `interact_teach.py` script.
Those will be used to initialize the configuration and load the checkpoint.

Then, you can run the demo  :)

**Comment by opentld** [comment] 2022-10-07 16:25
I got the .hydra/config.yaml and checkpoints/last.ckpt,and put pkl into data folder like this:
![image](https://user-images.githubusercontent.com/21096515/194601771-3f04b310-9e37-4978-8820-040f95e0445e.png)
but another error occurs:

(teach-env) D:\SourceCodes\Pose\3D\teach>python interact_teach.py folder=./ output=./ texts=run durs=3
Global seed set to 1234
[08/10/22 00:05:02][__main__][INFO] - Loading model
Error executing job with overrides: ['folder=./', 'output=./', 'texts=run', 'durs=3']
Traceback (most recent call last):
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "D:\SourceCodes\Pose\3D\teach\teach\transforms\rots2joints\smplh.py", line 58, in __init__
    self.smplh = SMPLHLayer(path, ext="pkl", gender=gender).eval()
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\smplx\body_models.py", line 761, in __init__
    super(SMPLHLayer, self).__init__(
  File "D:\DevelopTools\anaconda3\envs\teach-env\lib\site-packages\smplx\body_models.py", line 601, in __init__
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'

**Comment by atnikos** [comment] 2022-10-07 18:56
You have to follow the procedure described [here in the last comment](https://github.com/athn-nik/teach/issues/2) to get the right SMPLH_MALE model. I should include this in the repo.

**Comment by opentld** [comment] 2022-10-08 03:11
I'm using windows10 and Anaconda, so I have to make some change like this:
![image](https://user-images.githubusercontent.com/21096515/194684777-91a9cee6-88cf-4d9e-af2b-c5cc642ca74d.png)
This is because the path separator for Windows is different from Linux, so I have to convert '\\' to '/'
and, in mesh_viz.py, comment out the code    os.environ['PYOPENGL_PLATFORM'] = 'egl'    ,because windows does not support EGL.
After the above operations, the code runs.

(teach-env) D:\SourceCodes\Pose\3D\teach>python interact_teach.py folder=./ output=./outputs/ texts=[run,walk] durs=[5,5]
Global seed set to 1234
[08/10/22 10:55:46][__main__][INFO] - Loading model
[08/10/22 10:55:47][__main__][INFO] - Model 'teach' loaded
[08/10/22 10:55:48][__main__][INFO] - Model weights restored
Global seed set to 0
WARNING: You are using a SMPL+H model, with only 10 shape coefficients.

How about the WARRNING?
Is it because I change the code in mesh_viz.py ?
    smpl = get_body_model(path=f'{get_original_cwd()}/data/smpl_models',
                          model_type='smplh', gender='male',
                          batch_size=1, device='cpu')
I can't find the smpl_neutral.pkl, so I used smplh_male.pkl instead.

**Comment by atnikos** [comment] 2022-10-08 12:53
Yes, you are right the code has been tested on Ubuntu 20.04. You should use the male model as you can see in the [config](https://github.com/athn-nik/teach/blob/6dc5da01e9b7034e8f6148f8608b7c7a896487a8/configs/data/babel-amass.yaml#L6). The warning caused by smplx package. It is not something you should worry about. It just notifies you about the shape parameters used which are not important for this project.

**Comment by atnikos** [comment] 2022-10-08 12:54
I will keep this open, update the instructions and close this after. Let me know if you face any other problem.

**Comment by pfeducode** [comment] 2022-10-11 11:50
An error occurred in opengl. I don't know why？
![2022-10-11_19-46](https://user-images.githubusercontent.com/100210045/195082200-33354253-2217-4939-941c-c40b8ac90cc9.png)
![2022-10-11_19-47](https://user-images.githubusercontent.com/100210045/195082227-627aeff9-f67b-4d08-8763-08e001bc5776.png)

**Comment by atnikos** [comment] 2022-10-11 12:41
Hmmm, I am not sure at all. But can you try adding this line after package imports?
`os.environ['PYOPENGL_PLATFORM'] = 'egl'`
and let me know if it works.

**Comment by pfeducode** [comment] 2022-10-12 01:35
> Hmmm, I am not sure at all. But can you try adding this line after package imports? `os.environ['PYOPENGL_PLATFORM'] = 'egl'` and let me know if it works.

NO, it does not work. I think it's because of the version of opengl. I suggest using a more compatible pytorch3d

**Comment by atnikos** [comment] 2022-10-12 14:31
Can you try again using my environment? (i.e. no conda) Just follow the README instructions.
Run this: `source scripts/install.sh` and will create and activate the environment automatically for you then run the code and check if there is a bug. Sorry, but I do not trust conda.

**Comment by pfeducode** [comment] 2022-10-14 09:12
> Can you try again using my environment? (i.e. no conda) Just follow the README instructions. Run this: `source scripts/install.sh` and will create and activate the environment automatically for you then run the code and check if there is a bug. Sorry, but I do not trust conda.

no,it does not work, I have this problem in other projects. I think it's problem of PyOpenGL

**Comment by zhuangzhuang000** [comment] 2022-10-18 06:42
hello! 
I have obtained the SMPLH_MALE.pkl, but it is shown here that is required SMPL_NEUTRAL.pkl, where should I get it?


![image](https://user-images.githubusercontent.com/53167695/196354062-03aaba9e-55a2-4f74-8f52-08a5f5234ead.png)

**Comment by FusionLi** [comment] 2022-10-18 11:38
> 

@opentld Did you change the path separator on Windows for every file?

**Comment by atnikos** [comment] 2022-10-18 11:54
@zhuangzhuang000 you can obtain it [here](https://smpl.is.tue.mpg.de/). 
I have fixed it to use smplh male model. You can either download smpl neutral or pull my changes

**Comment by atnikos** [comment] 2022-10-18 21:46
I have tested the solution, it works only with smplh now so it should be good to go

**Closed as completed by atnikos** 2022-10-18 21:46 UTC
